### PR TITLE
pool _fill_free fix (fixes #71)

### LINKED ISSUE #71: If several tasks call Pool.acquire simultaneously, task hang occurs randomly.
Assume that there are task1, task2, task3 (Let's call that T1, T2, T3. and they use RedisPool) and self.minsize=1, self.maxsize=2 of Pool. (self.freesize = 1, self.size = 1)

While T1 acquired connection, T2 requests a connection to pool. (self.freesize = 0, self.size = 1)
```python
    # Pool.acquire() -> Pool._fill_free()
    @asyncio.coroutine
    def _fill_free(self):
        while self.freesize < self.minsize and self.size < self.maxsize:
            conn = yield from self._create_new_connection()     <------------ (1) T2
            yield from self._pool.put(conn)


```
While pending T2 at (1), T3 requests a connection to pool and suspends at (1) and T1 release a connection. (self.freesize = 1, self.size = 1)
And then, T2 resume, acquire and release a connection (self.freesize = 2, self.size = 2)
```python
    # Pool.acquire() -> Pool._fill_free()
    @asyncio.coroutine
    def _fill_free(self):
        while self.freesize < self.minsize and self.size < self.maxsize:
            conn = yield from self._create_new_connection()     <------------ (1) T3
            yield from self._pool.put(conn)                     
```

If T3 resumes, T3 tries to put a new connection to pool. However, T3 hangs until some task acquire connection, because it exceeds Maxsize of Pool.

### PR DESCRIPTION
**Pull request by kernel0**
fix about #71

### CODE REVIEW

**Comment by popravich** [comment]
Hi, @kernel0,
Thanks for PR.
I know about this problem for a while but had no time to fix it properly.
Regarding the fix, it should be a bit more complex:
you solved the problem of stucking `_pool.put` call but not the problem of creating and closing multiple connections to Redis.
The better way to fix it is to use some locking mechanism to prevent `_pool` queue overflow.

**Comment by kernel0** [comment]
Outlook에서 보냄




On Tue, Jul 28, 2015 at 11:22 PM -0700, "Alexey Popravka" <notifications@github.com> wrote:












Hi, @kernel0,

Thanks for PR.

I know about this problem for a while but had no time to fix it properly.

Regarding the fix, it should be a bit more complex:

you solved the problem of stucking _pool.put call but not the problem of creating and closing multiple connections to Redis.

The better way to fix it is to use some locking mechanism to prevent _pool queue overflow.

**Comment by kernel0** [comment]
Thanks for your review!! I'll think about the better way.
For now, I'll close this PR.

**Comment by asvetlov** [comment]
@kernel0 please take a look on `aiopg` pool for inspiration: https://github.com/aio-libs/aiopg/blob/master/aiopg/pool.py

**Comment by kernel0** [comment]
@asvetlov thank you!

**Pull request closed without merging**
