### PR TITLE
Url parser

### LINKED ISSUE #235: Created a redis url parser for aioredis
Let me know if it'd be helpful to submit this as part of a PR. It's modeled after [`redis-py`](https://github.com/andymccurdy/redis-py/blob/master/redis/connection.py#L777) and fully tested.

### PR DESCRIPTION
**Pull request by popravich**
Resolves #235 

TODO:
* [x] impement parser
* [x] add tests
* [x] update docs/examples

### CODE REVIEW

**Comment by kxepal** [comment]
Why not yarl? (:

**Comment by popravich** [comment]
1. I didn't want to add another dependency (+yarl dependencies)
2. yarl sets password to `None` if user field is empty

**Comment by asvetlov** [comment]
Yarl supports passwords without user but i undrestand your point

**Comment by popravich** [comment]
Then, probably, docs are outdated

**Pull request merged**
