### PR TITLE
fix util.decode to decode dicts also

### PR DESCRIPTION
**Pull request by alefteris**
Modified `aioredis.util.decode` to also decode dicts in responses recursively.

### CODE REVIEW

**Comment by popravich** [comment]
I don't remember any commands returning dics. What are they?

**Comment by alefteris** [comment]
@popravich `hgetall` returns a dict.

**Comment by popravich** [comment]
Redis `HGETALL` command returns array reply,
aioredis `Redis.hgetall` method converts such array reply into dict, decoding is supported as well.

**Comment by alefteris** [comment]
I'm so sorry. Somehow I didn't set the decode for Redis.hgetall and I thought there was an issue with the returned dict. Closing.

**Comment by popravich** [comment]
no problem

**Pull request closed without merging**
