### PR TITLE
fix for sensitive logging

### PR DESCRIPTION
**Pull request by marcstreeter**
no longer logs password as requested in issue https://github.com/aio-libs/aioredis/issues/399

### CODE REVIEW

**Comment by popravich** [comment]
Can you please add add a test capturing and checking this log message.
Logs can be captured like this https://github.com/aio-libs/aioredis/blob/master/tests/pool_test.py#L469-L479
and password setup can look like this https://github.com/aio-libs/aioredis/blob/master/tests/connection_test.py#L266-L291

**Comment by marcstreeter** [comment]
Oops - right, I should provide the tests.  I’ll come back to it.  I hit a snag trying to figure out how I’d test if the password was included in the log.  The examples you showed me (as well as the other tests I searched through) only seem to pass the password via the kwargs and not the address string (only host and port are being passed there it seems).

**Comment by popravich** [comment]
Are you talking about this — `redis://:passwd@host:1234/`?

**Comment by blueyed** [comment]
Please use pytest's `caplog` for the tests.
(`pytest.log` is added by aioredis)

**Pull request merged**
