### PR TITLE
Implement iscan, izscan, isscan, ihscan commands

### PR DESCRIPTION
**Pull request by asvetlov**
Support `async for` in scan commands

### CODE REVIEW

**Comment by asvetlov** [comment]
@popravich please review

**Comment by popravich** [comment]
It looks like `_*ScanIter` classes are almost the same, I think it would be better to leave just few of them and place in `util.py`

**Comment by asvetlov** [comment]
@popravich fixed

**Comment by popravich** [comment]
nice)

**Comment by asvetlov** [comment]
Cool! I have nothing more on my plate.
Could you make a release?

**Comment by popravich** [comment]
WIll do release in a day or two, still need to do #87

**Comment by asvetlov** [comment]
Sounds good!

**Comment by popravich** [comment]
I just had a little time) so it published

**Pull request merged**
