### PR TITLE
fix NoneType object is not iterable when iterate over self._waiters

### PR DESCRIPTION
**Pull request by jeffguorg**
## What do these changes do?

#726 fix a problem lead by python3.8

## Are there changes in behavior for the user?

nope

## Related issue number

#726 

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is `<Name> <Surname>`.
  * Please keep alphabetical order, the file is sorted by names. 
- [x] Add a new news fragment into the [`CHANGES/`](../tree/master/CHANGES) folder
  * name it `<issue_id>.<type>` (e.g. `588.bugfix`)
  * if you don't have an `issue_id` change it to the pr id after creating the PR
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example:
   `Fix issue with non-ascii contents in doctest text files.`

### CODE REVIEW

**Comment by jeffguorg** [comment]
Hi there

this is a fix for #726. no changes in behavier for users. i just don't know if i should add a line or a file in CHANGES for this is my first time contributing to aioredis. CHANGES directory seems to be empty for now.

**Comment by Andrew-Chen-Wang** [comment]
@jeffguorg It seems like the linters got ya. Install flake8 and run `flake8 *` for your python files. It should pass the test after that.

**Comment by jeffguorg** [comment]
@Andrew-Chen-Wang 

Hi, thanks. and i updated my pr. but i see some checks still fails after that. does that matter?

**Comment by Andrew-Chen-Wang** [comment]
@jeffguorg Yes. Take a look below these comments, and you'll see all the CI tests. Press "Details" for the Travis CI one and check each traceback error when you load the log.

**Comment by jeffguorg** [comment]
@Andrew-Chen-Wang Hi, thanks for your guidance and sorry i was busy working for some other issues.

I see that there are two issues.

one issue is about timeline protection. but there is no files in CHANGES directory and CHANGES.txt was not updated for months. where should i put the description?

another is about tests against test/*.py. one of the test failed. the line looks like this:
    E       assert 44087 != 44087
but i didn't find that line in the tests

**Comment by Andrew-Chen-Wang** [comment]
The line is `tests/sentinel_failover_test.py:55: AssertionError`.

You'll see the lines of failure as red and right below the printed code. Don't worry about timeline protection as that's not required.

**Comment by jeffguorg** [comment]
@Andrew-Chen-Wang 

sorry I was not responding for a period.

yes. I see that the test case is located in tests/sentinel_failover_test.py:55. I misunderstood the output. the assertion line is ```assert master.address[1] != old_port```.

but I have no clue why it is failing. nothing about cluster failover had been changed. is it possible that the test case has flaws?

**Comment by Andrew-Chen-Wang** [comment]
@jeffguorg Not a problem. It's open source volunteering after all :)

Can you try running the test case on your local machine? You can try it using this documentation: https://aioredis.readthedocs.io/en/v1.3.0/devel.html or perhaps just run `python setup.py`. After that, it's just a lot of `print()` statements and figuring out where it's going wrong.

You've only taken a look at that single travis build. There are other Travis builds that have other issues. Although I'm not entirely sure how Python 3.9 got in there... perhaps it's not something this PR should be concerned over.

**Review by CatCanCreate — APPROVED** [review]
LGTM!

**Comment by seandstewart** [comment]
@jeffguorg -

We can ignore the CI failures for now. Once you've followed the checklist (be sure to add a file to `CHANGES` and add yourself as a contributor!) we can get this merged.

**Comment by jeffguorg** [comment]
@seandstewart 
Hi, thanks for your guidance

this is my first time committing to a public repo. i added CHANGES/726.bugfix. is it good enough to merge into the repo?

**Comment by seandstewart** [comment]
> [CLA assistant check](https://cla-assistant.io/aio-libs/aioredis?pullRequest=727)
> Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/aio-libs/aioredis?pullRequest=727) before we can accept your contribution.
> **1** out of **2** committers have signed the CLA.
> 
> ✅ seandstewart
> ❌ Chao Guo
> **Chao Guo** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aio-libs/aioredis?pullRequest=727) it.

@jeffguorg looks like you still need to sign the CLA

**Comment by jeffguorg** [comment]
@seandstewart done!

I've signed the cla for long. it turns out that I was coding at my office so the commit author was wrong. the bot didn't recognize it. lol

**Comment by vinger4** [comment]
When the next release will possible?

**Pull request merged**
