### PR TITLE
Add xdel and xtrim

### PR DESCRIPTION
**Pull request by curiouscod3**
## What do these changes do?

Added xdel and xtrim method which missed in commands/streams.py.
And Also added unit test code of them.

## Are there changes in behavior for the user?

I don't think so, it is just additional methods missed.

## Related issue number

438
[https://github.com/aio-libs/aioredis/issues/438](https://github.com/aio-libs/aioredis/issues/438)

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is `<Name> <Surname>`.
  * Please keep alphabetical order, the file is sorted by names. 
- [x] Add a new news fragment into the [`CHANGES/`](../tree/master/CHANGES) folder
  * name it `<issue_id>.<type>` (e.g. `588.bugfix`)
  * if you don't have an `issue_id` change it to the pr id after creating the PR
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example:
   `Fix issue with non-ascii contents in doctest text files.`

### CODE REVIEW

**Comment by curiouscod3** [comment]
I think It works in my dev environment.

**Comment by gyermolenko** [comment]
unfortunately it fails flake checks and because of that it never got to tests stage in CI

**Comment by NiNJAD3vel0per** [comment]
> unfortunately it fails flake checks and because of that it never got to tests stage in CI

@gyermolenko  I will fix it to not fail flake checks

**Comment by curiouscod3** [comment]
> unfortunately it fails flake checks and because of that it never got to tests stage in CI

@gyermolenko I've fixed it !

**Comment by curiouscod3** [comment]
@gyermolenko  
Could you Please Allow this feature ?  I've tried to pass CI several times; 
it is hard to pass even though my code has no problem.
As matter of fact, the methods that I wrote are perfectly okay.
What is your suggestion or tips ? I might as well stop to try to pass CI.

**Comment by popravich** [comment]
Thanks

**Pull request merged**
