### PR TITLE
add client name to connection and connection pool

### LINKED ISSUE #713: Support client name part of Pool & Connection
I'd like to set in my application a client name for my connections. This is supported via the commands, but when using the Pool/Connection object it sometimes reconnect/creates new connections hence losing the set name.
This feature also exists in py-redis and makes a lot of sense - you set it once in the initialization of the Pool/Connection and it sets it after connecting.

PR incoming

### PR DESCRIPTION
**Pull request by aviramha**
## What do these changes do?

The changes add client name option to connection and connection pool so it's persistent across connections.
Fixes #713 

## Are there changes in behavior for the user?
No

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [X] Documentation reflects the changes
- [X] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`

- [X] Add a new news fragment into the [`CHANGES/`](../tree/master/CHANGES) folder

### CODE REVIEW

**Comment by aviramha** [comment]
#713

**Comment by aviramha** [comment]
Failed tests seems to be unrelated to the change..
@popravich could you review please?

**Comment by bharel** [comment]
@aviramha publish a null-change to re-run tests. Seems like pypy tests were broken when you pushed the patch.

**Comment by seandstewart** [comment]
@aviramha -

Thank you for your contribution and apologies for the radio silence! Maintenance for this project has resumed.

Would you be willing to resolve your merge conflicts? CI will fail for now but that's okay - we're going to fix that in a separate issue.

**Comment by aviramha** [comment]
@seandstewart Great to hear that! I'll fix this soon.

**Comment by seandstewart** [comment]
@aviramha - great! thanks for merging in master. Last thing to do is sign the CLA then I think we can move forward with a merge 👍

**Comment by aviramha** [comment]
@seandstewart I signed it.
Thanks for restoring maintenance!!

**Pull request merged**
